apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.serviceName }}
  namespace: ${{ values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ${{ values.serviceHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.serviceName }}
                port:
                  number: ${{ values.servicePort }}
