apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentName }}
  title: ${{ values.componentTitle }}
  description: >
    ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - azure-devops
    - generated
    - service
spec:
  type: service
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
  system: ${{ values.system }}
  dependsOn:
    - resource:default/${{ values.azureDevOpsProject }}
